
GET http://localhost:8080/admin/card/100 HTTP/1.1
content-type: application/json

###

GET http://localhost:8080/admin/card/100/balance HTTP/1.1
content-type: application/json

###

POST http://localhost:8080/admin/card HTTP/1.1
content-type: application/json

{
    "external_id": 100,
    "name": "Pedro Faria",
    "enabled": true
}

###

POST http://localhost:8080/card/100/deposit HTTP/1.1
content-type: application/json

{
    "amount": 5.70,
    "paid": true
}