// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: queries.sql

package ledger

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createLedger = `-- name: CreateLedger :exec

INSERT INTO
    ledgers (
        id,
        card_id,
        reference,
        reference_id,
        amount,
        created_at
    )
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateLedgerParams struct {
	ID          uuid.UUID
	CardID      uuid.UUID
	Reference   Reference
	ReferenceID uuid.UUID
	Amount      string
	CreatedAt   time.Time
}

func (q *Queries) CreateLedger(ctx context.Context, db DBTX, arg CreateLedgerParams) error {
	_, err := db.ExecContext(ctx, createLedger,
		arg.ID,
		arg.CardID,
		arg.Reference,
		arg.ReferenceID,
		arg.Amount,
		arg.CreatedAt,
	)
	return err
}

const increaseCardBalance = `-- name: IncreaseCardBalance :exec

UPDATE balances SET amount = amount + $1 WHERE card_id = $2
`

func (q *Queries) IncreaseCardBalance(ctx context.Context, db DBTX, amount string, cardID uuid.UUID) error {
	_, err := db.ExecContext(ctx, increaseCardBalance, amount, cardID)
	return err
}
