// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Deposit struct {
	ID         uuid.UUID
	ExternalID uuid.UUID
	CardID     uuid.UUID
	Amount     string
	Paid       bool
	Cancelled  bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
