// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: queries.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cancelDepositById = `-- name: CancelDepositById :one

UPDATE deposits
SET cancelled = true
WHERE
    id = $1
    AND cancelled = false RETURNING id, external_id, card_id, amount, paid, cancelled, created_at, updated_at
`

func (q *Queries) CancelDepositById(ctx context.Context, id uuid.UUID) (Deposit, error) {
	row := q.db.QueryRowContext(ctx, cancelDepositById, id)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.CardID,
		&i.Amount,
		&i.Paid,
		&i.Cancelled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDeposit = `-- name: CreateDeposit :exec

INSERT INTO
    deposits (
        id,
        external_id,
        card_id,
        amount,
        paid,
        created_at,
        updated_at
    )
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateDepositParams struct {
	ID         uuid.UUID
	ExternalID uuid.UUID
	CardID     uuid.UUID
	Amount     string
	Paid       bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) CreateDeposit(ctx context.Context, arg CreateDepositParams) error {
	_, err := q.db.ExecContext(ctx, createDeposit,
		arg.ID,
		arg.ExternalID,
		arg.CardID,
		arg.Amount,
		arg.Paid,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getDepositByExternalId = `-- name: GetDepositByExternalId :one

SELECT id, external_id, card_id, amount, paid, cancelled, created_at, updated_at FROM deposits WHERE external_id = $1
`

func (q *Queries) GetDepositByExternalId(ctx context.Context, externalID uuid.UUID) (Deposit, error) {
	row := q.db.QueryRowContext(ctx, getDepositByExternalId, externalID)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.CardID,
		&i.Amount,
		&i.Paid,
		&i.Cancelled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDepositsByExternalCardId = `-- name: GetDepositsByExternalCardId :many

SELECT d.id, d.external_id, d.card_id, d.amount, d.paid, d.cancelled, d.created_at, d.updated_at
FROM cards c
    INNER JOIN deposits d ON d.card_id = c.id
WHERE c.external_id = $1
`

func (q *Queries) GetDepositsByExternalCardId(ctx context.Context, externalID int32) ([]Deposit, error) {
	rows, err := q.db.QueryContext(ctx, getDepositsByExternalCardId, externalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deposit
	for rows.Next() {
		var i Deposit
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.CardID,
			&i.Amount,
			&i.Paid,
			&i.Cancelled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaidActiveDepositById = `-- name: UpdatePaidActiveDepositById :exec

UPDATE deposits SET paid = $2 WHERE id = $1 AND cancelled = false
`

func (q *Queries) UpdatePaidActiveDepositById(ctx context.Context, iD uuid.UUID, paid bool) error {
	_, err := q.db.ExecContext(ctx, updatePaidActiveDepositById, iD, paid)
	return err
}
