// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package cards

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CancelDepositByExternalId(ctx context.Context, externalID uuid.UUID) (Deposit, error)
	CreateBalance(ctx context.Context, arg CreateBalanceParams) error
	CreateCard(ctx context.Context, arg CreateCardParams) error
	CreateDeposit(ctx context.Context, arg CreateDepositParams) error
	CreateLedger(ctx context.Context, arg CreateLedgerParams) error
	GetCard(ctx context.Context, id uuid.UUID) (Card, error)
	GetCardBalance(ctx context.Context, cardID uuid.UUID) (string, error)
	GetCardByExternalId(ctx context.Context, externalID int32) (Card, error)
	GetCardFull(ctx context.Context, id uuid.UUID) (GetCardFullRow, error)
	GetCardFullByExternalId(ctx context.Context, externalID int32) (GetCardFullByExternalIdRow, error)
	GetCardIdByExternalId(ctx context.Context, externalID int32) (uuid.UUID, error)
	GetDepositsByExternalCardId(ctx context.Context, externalID int32) ([]Deposit, error)
	IncreaseCardBalance(ctx context.Context, arg IncreaseCardBalanceParams) error
	UpdateEnabledCardByExternalId(ctx context.Context, arg UpdateEnabledCardByExternalIdParams) error
	UpdatePaidActiveDepositByExternalId(ctx context.Context, arg UpdatePaidActiveDepositByExternalIdParams) error
}

var _ Querier = (*Queries)(nil)
